"use client";
import { FileText, Search, Trash2 } from "lucide-react";
import { useEffect, useState } from "react";
import { PageHeader } from "./DashboardView";

export function HistoryView({ history, query, deletedHistory, onQueryChange, onDelete, onUndoDelete, onRestore }) {
  const [page, setPage] = useState(0);
  const [writes, setWrites] = useState([]);
  useEffect(() => { fetch("/api/google/audit").then((r) => r.json()).then((d) => setWrites(d.writes || [])).catch(() => {}); }, []);
  const filtered = history.filter((entry) => !query.trim() || [entry.workDate, entry.summary, ...(entry.repos || [])].join(" ").toLowerCase().includes(query.trim().toLowerCase()));
  const pageSize = 20, pageCount = Math.max(1, Math.ceil(filtered.length / pageSize)), visible = filtered.slice(page * pageSize, (page + 1) * pageSize);
  const days = [...history].sort((a, b) => a.workDate.localeCompare(b.workDate)).slice(-14);
  const max = Math.max(1, ...days.map((e) => (e.commitCount || 0) + (e.pullRequestCount || 0)));
  const commits = history.reduce((n, e) => n + (e.commitCount || 0), 0), prs = history.reduce((n, e) => n + (e.pullRequestCount || 0), 0), repos = new Set(history.flatMap((e) => e.repos || [])).size;
  return <><PageHeader eyebrow="History / Saved worklogs" title="Summary history" subtitle="Find, review, and restore previous worklogs." /><div className="page-scroll"><div className="history-page panel"><div className="activity-overview"><div><span>Commits</span><strong>{commits}</strong></div><div><span>Pull requests</span><strong>{prs}</strong></div><div><span>Active days</span><strong>{history.length}</strong></div><div><span>Repositories</span><strong>{repos}</strong></div></div>{days.length > 0 && <section className="activity-chart"><div className="panel-eyebrow">Activity by day</div><div className="chart-bars">{days.map((entry) => { const total = (entry.commitCount || 0) + (entry.pullRequestCount || 0); return <div className="chart-day" title={`${entry.workDate}: ${entry.commitCount || 0} commits, ${entry.pullRequestCount || 0} PRs`} key={entry.id}><div className="chart-bar" style={{ height: `${Math.max(8, total / max * 100)}%` }}><i style={{ height: `${total ? (entry.commitCount || 0) / total * 100 : 0}%` }} /></div><span>{entry.workDate.slice(5)}</span></div>; })}</div><small className="chart-legend">Green: commits · muted: pull requests</small></section>}{deletedHistory && <div className="undo-banner">History entry deleted. <button type="button" onClick={onUndoDelete}>Undo</button></div>}<div className="history-search-wrap"><Search size={15} /><input value={query} placeholder="Search date, repository, or summary" onChange={(e) => { setPage(0); onQueryChange(e.target.value); }} /></div>{!filtered.length ? <div className="empty-state"><FileText size={22} /><strong>{history.length ? "No matching summaries" : "No summaries yet"}</strong></div> : <><div className="history-page-list">{visible.map((entry) => <article className="history-page-row" key={entry.id}><button type="button" onClick={() => onRestore(entry)}><strong>{entry.workDate}</strong><span>{entry.repos?.join(", ") || "Saved worklog"} · {entry.commitCount || 0} commits · {entry.pullRequestCount || 0} PRs</span><p>{entry.summary}</p></button><button className="icon-button danger" aria-label={`Delete summary for ${entry.workDate}`} type="button" onClick={() => onDelete(entry.id)}><Trash2 size={15} /></button></article>)}</div><div className="history-pagination"><button className="secondary-button" disabled={!page} type="button" onClick={() => setPage((n) => n - 1)}>Previous</button><span>Page {page + 1} of {pageCount}</span><button className="secondary-button" disabled={page + 1 >= pageCount} type="button" onClick={() => setPage((n) => n + 1)}>Next</button></div></>}</div></div></>;
}
